[package]
name = "libfuzzer"
version = "0.1.0"
authors = ["Andrea Fioraldi <andreafioraldi@gmail.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["std"]
std = []

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
debug = true

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
num_cpus = "1.0"

[dependencies]
clap = "2.32.0"
afl = { path = "../../afl/", features = ["std", "runtime"] }

[[bin]]
name = "libfuzzer"
path = "./src/mod.rs"
test = false
bench = false